DED_FLAGS=-Wall -Wextra -Weffc++ -Wcast-align -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wfloat-equal -Wformat-security -Wformat=2 -Wignored-qualifiers -Winit-self -Winline -Wlogical-op -Wmain -Wmissing-declarations -Wno-missing-field-initializers -Wmissing-include-dirs -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wredundant-decls -Wshadow -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wswitch-default -Wswitch-enum -Wtype-limits -Wundef -Wunreachable-code -Wwrite-strings -fexceptions -g -pipe -D_DEBUG -D_EJUDGE_CLIENT_SIDE -D_EJC
FILE_OBJECTS=main.o stackConstructor.o stackDestructor.o stack_check.o stackDump.o stackPop.o stackPush.o comparing_numbers.o

all: stack
 
stack: main.o stackConstructor.o stackDestructor.o stack_check.o stackDump.o stackPop.o stackPush.o comparing_numbers.o
	@g++ $(DED_FLAGS) $(FILE_OBJECTS) -o stack

main.o: main.cpp
	@g++ $(DED_FLAGS) -c main.cpp -o main.o
	@echo "[CXX] main"

stackConstructor.o: stackConstructor.cpp
	@g++ $(DED_FLAGS) -c stackConstructor.cpp -o stackConstructor.o
	@echo "[CXX] stackConstructor"

stackDestructor.o: stackDestructor.cpp
	@g++ $(DED_FLAGS) -c stackDestructor.cpp -o stackDestructor.o
	@echo "[CXX] stackDestructor"

stack_check.o: stack_check.cpp
	@g++ $(DED_FLAGS) -c stack_check.cpp -o stack_check.o
	@echo "[CXX] stack_check"

stackDump.o: stackDump.cpp
	@g++ $(DED_FLAGS) -c stackDump.cpp -o stackDump.o
	@echo "[CXX] stackDump"

stackPop.o: stackPop.cpp
	@g++ $(DED_FLAGS) -c stackPop.cpp -o stackPop.o
	@echo "[CXX] stackPop"

stackPush.o: stackPush.cpp
	@g++ $(DED_FLAGS) -c stackPush.cpp -o stackPush.o
	@echo "[CXX] stackPush"

comparing_numbers.o: comparing_numbers.cpp
	@g++ $(DED_FLAGS) -c comparing_numbers.cpp -o comparing_numbers.o
	@echo "[CXX] comparing_numbers"

clean:
	rm -rf *.o
	rm -rf *.exe